[workspace]
members = [
  "./crates/protobuf-mapper",
  "./crates/protobuf-mapper-codegen",
  "./crates/protobuf-mapper-tests",
]

[patch.crates-io]
protobuf-mapper-codegen = { path = "./crates/protobuf-mapper-codegen" }
